### PR TITLE
Get and display network IP address in server

### PR DESCRIPTION
**Pull request by muratpurc**
This comes in handy if you run the app within a virtual maschine or a container but need to access it from the host.

### CODE REVIEW

**Comment by tipiirai** [comment]
Thanks! Possible to edit the code so that there is no " or " sentence? Just show the address and port that is in use.

**Comment by muratpurc** [comment]
Your welcome. The ' or ' part has been removed, the output now looks like this:

````
Node HTTP server at http://127.0.0.1:8080/ http://x.x.x.x:8080/
````
(where `x.x.x.x` is the IP of your container or vm)

By the way, NueJS is a great project, I wish you much success with it.

**Comment by tipiirai** [comment]
So we need to display both addresses and not just the other one when found? (Sorry, not familiar with containers)

And unfortunately, this now creates a conflict after merging #16! Can I ask you to update this one more time? 🙏

> By the way, NueJS is a great project, I wish you much success with it.

Thanks a lot! Good to hear.

**Comment by tipiirai** [comment]
Thank you!

**Pull request merged**
