### PR TITLE
feat: add `create-nue` cli to create nue project

### PR DESCRIPTION
**Pull request by ErKeLost**
I created a scaffolding to help nue build the project quickly, hoping to help the ecology of nue.  😊

image

### CODE REVIEW

**Comment by tipiirai** [comment]
Wow. Quite a big chunk of work in here! I just saw this now since I have been hanging around in the nuejs repository only. I think big changes like these should be discussed first. For example, I see some things that are not quite in line with the spirit of Nue: like adding multiple dependencies to package.json and all Nue projects are currently written in JavaScript and not TypeScript. I would also use Node's native [parseArgs](https://nodejs.org/api/util.html#utilparseargsconfig)

**Comment by ErKeLost** [comment]
> Wow. Quite a big chunk of work in here! I just saw this now since I have been hanging around in the nuejs repository only. I think big changes like these should be discussed first. For example, I see some things that are not quite in line with the spirit of Nue: like adding multiple dependencies to package.json and all Nue projects are currently written in JavaScript and not TypeScript. I would also use Node's native [parseArgs](https://nodejs.org/api/util.html#utilparseargsconfig)

Thank you for your reply. At present, the scaffolding tool is just whether the scaffolding tool is written in ts to write the resulting nue template or js. The native node parameter parsing you said is also a good way.

**Comment by tipiirai** [comment]
Thanks! This create-nue project is ultimately written with [Nuekit](//nuejs.org/tools/#nuekit) which will be in charge of the command line interface. I'm hesitant to introduce heavy scaffolding/CLI tools before that. Does it make sense?

**Comment by ErKeLost** [comment]
If we are going to end up with a cli tool that is similar to vite in a very wide range of areas, I would recommend using it.

**Comment by ErKeLost** [comment]
`create-nue`, I created this package on npm. I can delete it at any time if you need it.

**Comment by tipiirai** [comment]
@ErKeLost  Please remove the create-nue package from npm. I was about to push a new version there but it was prohibited. How were you able to override the existing npm package? Thanks!

**Comment by ErKeLost** [comment]
> @ErKeLost Please remove the create-nue package from npm. I was about to push a new version there but it was prohibited. How were you able to override the existing npm package? Thanks!请从 npm 中删除创建 nue 包。我正要在那里推送一个新版本，但它被禁止了。你是如何覆盖现有的 npm 包的？谢谢！

ok If you're ready, I'll delete it now.

**Comment by tipiirai** [comment]
Doing that now

**Comment by tipiirai** [comment]
Damn. It gave me this:

npm ERR! code E403
npm ERR! 403 403 Forbidden - PUT https://registry.npmjs.org/create-nue - create-nue cannot be republished until 24 hours have passed.
npm ERR! 403 In most cases, you or one of your dependencies are requesting
npm ERR! 403 a package version that is forbidden by your security policy, or
npm ERR! 403 on a server you do not have access to.

**Comment by ErKeLost** [comment]
> Damn. It gave me this:
> 
> npm ERR! code E403 npm ERR! 403 403 Forbidden - PUT https://registry.npmjs.org/create-nue - create-nue cannot be republished until 24 hours have passed. npm ERR! 403 In most cases, you or one of your dependencies are requesting npm ERR! 403 a package version that is forbidden by your security policy, or npm ERR! 403 on a server you do not have access to.

I think it's because I just deleted it and I have to wait 24 hours. I'm so sorry.

**Comment by tipiirai** [comment]
No worries! Thank you for the co-operation!

**Comment by ErKeLost** [comment]
> No worries! Thank you for the co-operation!

its my pleasure thanks

**Pull request closed without merging**
