### PR TITLE
fix: Compatible with npx

### PR DESCRIPTION
**Pull request by gucovip**
fix compatible with npx

### CODE REVIEW

**Comment by gucovip** [comment]
Temporarily use `npx` to overdo it. [nue issue #110](https://github.com/nuejs/nue/issues/110)
`npx create-nue@latest`

**Comment by tipiirai** [comment]
Gotcha. Makes sense. Isn't `'use strict'` unnecessary with ES6 modules?

**Comment by gucovip** [comment]
@tipiirai OK. I've removed the `'use strict'`.

**Comment by tipiirai** [comment]
Hey. Added `#!/usr/bin/env bun` to cli.js and `bun create` started to work! Works on the latest version (`bun create nuekit@latest`. Thanks to the inspiration of this pull request. Thank you @gucovip !

**Pull request closed without merging**
